### ISSUE TITLE
Problem installing gem 

### ISSUE THREAD

**Issue by christian** [Hanmac/libarchive-ruby#1]
Hello,

I'm trying to install the gem using:

```
 gem install libarchive-ruby
```

using this version of Ruby:

```
 ruby 1.8.7 (2010-04-19 patchlevel 253) [i686-darwin10.4.0], MBARI 0x6770, Ruby Enterprise Edition 2010.02
```

I get:

```
ERROR:  Error installing libarchive-ruby:
libarchive-ruby requires Ruby version >= 1.9.
```

I saw on the last commit that you have changed minimum version of Ruby to 1.8.7. Maybe you forgot to push to Rubygems ?
On the docs on Rubygems the readme states that the minimum required version is 1.9 (http://rubydoc.info/gems/libarchive-ruby/0.0.2/frames)

BTW, the gem is awesome!!

Thanks, 
Cristi

**Comment by Hanmac** [comment]
rubygems got version 0.0.3 of this gem i added a fix around so it work with 1.8.7 .. but it work better with 1.9 :P

PS: i talked with debian-ruby some day a deb-package of this gem exist
