### ISSUE TITLE
Could you add support for handling string IO as archive Archive.new(stringio)?

### ISSUE THREAD

**Issue by msf1013** [Hanmac/libarchive-ruby#10]
Could you add support for handling string IO as archive Archive.new(stringio)?

**Comment by msf1013** [comment]
@Hanmac I saw this in a code comment as a TODO. May I ask, are you still planning to implement it?

**Comment by Hanmac** [comment]
StringIO normally should already work, i need to rewrote that lib because its already old and might have stuff that need to be replaced with newer one, but currently i dont have the time and my PC where i develop that stuff is currently broken

**Comment by msf1013** [comment]
@Hanmac Thanks for your answer, I understand. Just to make sure, is the Archive.new(stringio) functionality currently working? Because when I give the function a StringIO as parameter it warns me that there must be 3 parameters. What I would like is to handle the Archive in memory and extract its content without actually creating the .tar represented in the Archive.

**Comment by Hanmac** [comment]
if you use StringIO you might need the format as the second parameter, in your case it should be

``` ruby
Archive.new(stringio, :tar)
```

and as i said i need to check the repo and update it against newer code

**Comment by msf1013** [comment]
Thanks! I will give it a try.
