### ISSUE TITLE
libarchive-ruby crashes on directories

### ISSUE THREAD

**Issue by Quintus** [Hanmac/libarchive-ruby#3]
Hi there, 

The library crashes with a C++ exception if one tries to add a directory to an Archive object.

```
√ quintus@hades => ~/Desktop/foo
$ tree
.
└── foofoo
    └── test

1 directory, 1 file
√ quintus@hades => ~/Desktop/foo
$ cat foofoo/test 
test
√ quintus@hades => ~/Desktop/foo
$ ruby -rarchive -e 'a = Archive.new("test.tar.bz2"); a << "foofoo"'
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::append
Abgebrochen
√ quintus@hades => ~/Desktop/foo
$ 
```

ruby -v: `ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]`
gem -v: `1.8.10`
OS: Arch Linux
libarchive version: 2.8.4
libarchive-ruby version: 0.0.3

I had expected to either add the directory recursively to the archive, or to at least crash with a Ruby exception saying that directories cannot be included directly. Note that appending the `foofoo/test` file directly works without problems: 

```
√ quintus@hades => ~/Desktop/foo
$ rm test.tar.bz2 
√ quintus@hades => ~/Desktop/foo
$ ruby -rarchive -e 'a = Archive.new("test.tar.bz2"); a << "foofoo/test"'
√ quintus@hades => ~/Desktop/foo
$ tar -tjf test.tar.bz2 
foofoo/test
```

Valete, 
Marvin

**Comment by Hanmac** [comment]
it should work on directories, it works also nice with the new disk engine
